import csv
import time

import requests
from bs4 import BeautifulSoup

# URL principal que processa o formulário de pesquisa
URL_BUSCA = "https://sistemas.sefaz.am.gov.br/sgc-am/contratos.do"

# Dicionário com os códigos das Unidades Gestoras (UGs)
# Coloquei algumas de exemplo, mas você pode adicionar as outras do HTML
UNIDADES_GESTORAS = {
    "001701": "(FFAL) - FUNDO DE FOMENTO A ATIVIDADE LEGISLATIVA",
    "002701": "(FAECE) - FUNDO DE APOIO AO EXERCICIO DO CONTROLE EXTERNO",
    "011101": "(CASA CIVIL) - CASA CIVIL",
    "011103": "(PGE) - PROCURADORIA-GERAL DO ESTADO",
    "011104": "(OGE) - OUVIDORIA-GERAL DO ESTADO",
    "011108": "(CASA MILITAR) - CASA MILITAR",
    "011109": "(CGE) - CONTROLADORIA-GERAL DO ESTADO",
    "011120": "(SEGOV) - SECRETARIA DE GOVERNO",
    "011206": "(IO) - IMPRENSA OFICIAL DO ESTADO DO AMAZONAS",
    "011209": "(ARSEPAM) - AGÊNCIA REGULADORA DE SERVIÇOS PÚBLICOS DELEGADOS E CONTRATADOS DO ESTADO DO AMAZONAS",
    "011210": "(DETRAN-Am) - DEPARTAMENTO ESTADUAL DE TRÂNSITO",
    "011304": "(UEA) - UNIVERSIDADE DO ESTADO DO AMAZONAS",
    "011705": "(FPS) - SECRETARIA EXECUTIVA DO FUNDO DE PROMOÇÃO SOCIAL E ERRADICAÇÃO DA POBREZA",
    "011706": "(FUNDPGE) - FUNDO ESPECIAL DA PROCURADORIA-GERAL DO ESTADO",
    "012101": "(GVG) - SECRETARIA GERAL DA VICE-GOVERNADORIA",
    "013101": "(SEAD) - SECRETARIA DE ESTADO DE ADMINISTRAÇÃO E GESTÃO",
    "013102": "(CSC) - CENTRO DE SERVIÇOS COMPARTILHADOS",
    "013301": "(AMAZONPREV) - FUNDAÇÃO FUNDO PREVIDENCIÁRIO DO ESTADO DO AMAZONAS",
    "014101": "(SEFAZ) - SECRETARIA DE ESTADO DA FAZENDA",
    "014103": "(SEFAZ-EG) - SECRETARIA DE ESTADO DA FAZENDA - ENCARGOS GERAIS DO ESTADO",
    "014501": "(CADA) - COMPANHIA AMAZONENSE DE DESENVOLVIMENTO E MOBILIZAÇÃO DE ATIVOS",
    "014701": "(SEFAZ-FUNDO) - FUNDO PARA FINANCIAMENTO DA MODERNIZAÇÃO FAZENDÁRIA DO ESTADO DO AMAZONAS",
    "016101": "(SEDECTI) - SECRETARIA DE ESTADO DE DESENVOLVIMENTO ECONÔMICO, CIÊNCIA, TECNOLOGIA E INOVAÇÃO",
    "016201": "(JUCEA) - JUNTA COMERCIAL DO ESTADO",
    "016202": "(IPEM) - INSTITUTO DE PESOS E MEDIDAS",
    "016301": "(FAPEAM) - FUNDAÇÃO DE AMPARO À PESQUISA DO ESTADO DO AMAZONAS",
    "016508": "(AMAZONASTUR) - EMPRESA ESTADUAL DE TURISMO",
    "016702": "(FET) - FUNDO ESTADUAL DO TRABALHO DO ESTADO DO AMAZONAS",
    "016703": "(FUNECTI) - FUNDO ESTADUAL PARA O DESENVOLVIMENTO CIENTIFICO, TECNOLOGICO E DE INOVAÇÃO",
    "017101": "(SUSAM) - SECRETARIA DE ESTADO DE SAÚDE",
    "017102": "(CESMAM) - CENTRO DE SAUDE MENTAL DO AMAZONAS",
    "017103": "(PGGM) - POLICLÍNICA GOVERNADOR GILBERTO MESTRINHO",
    "017104": "(PAM CODAJAS) - POLICLÍNICA PAM - CODAJAS",
    "017105": "(HGGR) - HOSPITAL GERAL DR. GERALDO DA ROCHA",
    "017106": "(HICP) - HOSPITAL DE ISOLAMENTO CHAPOT PREVOST",
    "017107": "(PS 28 AGOSTO) - PRONTO SOCORRO 28 DE AGOSTO",
    "017109": "(ICAM) - INSTITUTO DE SAÚDE DA CRIANÇA DO AMAZONAS",
    "017110": "(PSC  SUL) - PRONTO SOCORRO DA CRIANÇA ZONA SUL",
    "017111": "(MBM) - MATERNIDADE BALBINA MESTRINHO",
    "017113": "(HPS JLUCIO) - HOSPITAL E PRONTO SOCORRO DR. JOÃO LÚCIO PEREIRA MACHADO",
    "017115": "(HPSC OESTE) - HOSPITAL E PRONTO SOCORRO DA CRIANÇA - ZONA OESTE",
    "017116": "(MAT ANA BRAGA) - MATERNIDADE DE REFERÊNCIA DA ZONA LESTE DE MANAUS - ANA BRAGA",
    "017117": "(HPSC ZONA LESTE) - HOSPITAL E PRONTO SOCORRO DA CRIANÇA - ZONA LESTE",
    "017118": "(PZL) - POLICLINICA ZENO LANZINE",
    "017119": "(PJSB) - POLICLINICA JOAO DOS SANTOS BRAGA",
    "017120": "(CAMI II) - MATERNIDADE DONA NAZIRA DAOU - CAMI II",
    "017121": "(MAM) - MATERNIDADE AZILDA MARREIRO",
    "017122": "(CAMI I) - MATERNIDADE DR. ANTENOR BARBOSA",
    "017123": "(SPA COROADO) - SERVIÇO DE PRONTO ATENDIMENTO - COROADO",
    "017124": "(SPA JOSÉ LINS) - SERVIÇO DE PRONTO ATENDIMENTO E POLICLÍNICA DR JOSÉ DE JESUS LINS DE ALBUQUERQUE",
    "017125": "(SPA DR PLATAO) - SERVIÇO DE PRONTO ATENDIMENTO E HOSPITAL DR ARISTOTELES PLATAO BEZERRA DE ARAUJO",
    "017126": "(SPA MADY) - SERVIÇO DE PRONTO ATENDIMENTO ELIAMEME RODRIGUES MADY",
    "017127": "(SPA SUL) - SERVIÇO DE PRONTO ATENDIMENTO ZONA SUL",
    "017128": "(SPA ALVORADA) - SERVIÇO DE PRONTO ATENDIMENTO - ALVORADA",
    "017129": "(SPA JOVENTINA) - SERVIÇO DE PRONTO ATENDIMENTO - JOVENTINA DIAS",
    "017130": "(CEMA) - CENTRAL DE MEDICAMENTOS DA SECRETARIA DE ESTADO DA SAUDE DO AMAZONAS",
    "017131": "(SPASR) - SERVIÇO DE PRONTO ATENDIMENTO SAO RAIMUNDO",
    "017132": "(SPADC) - SPA DANILO CORREA",
    "017133": "(IDM) - INSTITUTO DA MULHER",
    "017145": "(PLAALX) - POLICLINICA ANTONIO ALEIXO",
    "017146": "(HIDF) - HOSPITAL INFANTIL DR. FAJARDO",
    "017147": "(UPACS) - UNIDADE DE PRONTO ATENDIMENTO UPA 24HS CAMPOS SALES",
    "017148": "(UPACN) - UNIDADE DE PRONTO ATENDIMENTO UPA 24HS CIDADE NOVA",
    "017301": "(FCECON) - FUNDAÇÃO CENTRO DE CONTROLE DE ONCOLOGIA DO ESTADO DO AMAZONAS",
    "017302": "(FHEMOAM) - FUNDAÇÃO HOSPITALAR DE HEMATOLOGIA E HEMOTERAPIA DO AMAZONAS",
    "017303": "(FUHAM) - FUNDAÇÃO HOSPITALAR DE DERMATOLOGIA TROPICAL E VENEREOLOGIA \"ALFREDO DA MATTA\"",
    "017304": "(FMT) - FUNDAÇÃO DE MEDICINA TROPICAL \"DOUTOR HEITOR VIEIRA DOURADO\"",
    "017305": "(FHAJ) - FUNDAÇÃO HOSPITAL \"ADRIANO JORGE\"",
    "017306": "(FVS/AM) - FUNDAÇÃO DE VIGILÂNCIA EM SAÚDE DO ESTADO DO AMAZONAS DRA. ROSEMARY COSTA PINTO",
    "017307": "(FHCFM) - FUNDACAO HOSPITAL DO CORAÇÃO \"FRANCISCA MENDES\"",
    "017701": "(FES) - FUNDO ESTADUAL DE SAÚDE",
    "018101": "(SEPROR) - SECRETARIA DE ESTADO DE PRODUÇÃO RURAL",
    "018102": "(SEPA) - SECRETARIA DE ESTADO DE PESCA E AQUICULTURA",
    "018201": "(IDAM) - INSTITUTO DE DESENVOLVIMENTO AGROPECUÁRIO E FLORESTAL SUSTENTÁVEL DO ESTADO DO AMAZONAS",
    "018202": "(ADAF) - AGÊNCIA DE DEFESA AGROPECUÁRIA E FLORESTAL DO ESTADO DO AMAZONAS",
    "019101": "(SECT) - SECRETARIA DE ESTADO DAS CIDADES E TERRITÓRIOS",
    "019702": "(FERF) - FUNDO ESTADUAL DE REGULARIZAÇÃO FUNDIÁRIA",
    "020101": "(SEC) - SECRETARIA DE ESTADO DE CULTURA E ECONOMIA CRIATIVA",
    "020701": "(FEC) - FUNDO ESTADUAL DE CULTURA",
    "021101": "(SEJUSC) - SECRETARIA DE ESTADO DE JUSTIÇA, DIREITOS HUMANOS E CIDADANIA",
    "021111": "(UPI) - UNIDADES PRISIONAIS DO INTERIOR",
    "021202": "(PROCON-AM) - INSTITUTO DE DEFESA DO CONSUMIDOR - PROCON - AM",
    "021301": "(FEPIAM) - FUNDACAO ESTADUAL DOS POVOS INDIGENAS DO AMAZONAS",
    "021302": "(FUNATI) - FUNDAÇÃO UNIVERSIDADE ABERTA DA TERCEIRA IDADE",
    "021702": "(FUNDECON) - FUNDO ESTADUAL DE DEFESA DO CONSUMIDOR",
    "021703": "(FEAD) - FUNDO ESTADUAL ANTIDROGAS",
    "021704": "(FECA) - FUNDO ESTADUAL DA CRIANÇA E DO ADOLESCENTE",
    "021706": "(FEIAM) - FUNDO ESTADUAL DO IDOSO",
    "022101": "(SSP) - SECRETARIA DE ESTADO DE SEGURANÇA PÚBLICA",
    "022102": "(PC) - POLÍCIA CIVIL DO ESTADO DO AMAZONAS",
    "022103": "(PMAM) - POLÍCIA MILITAR DO ESTADO DO AMAZONAS",
    "022104": "(CBMAM) - CORPO DE BOMBEIROS MILITAR DO ESTADO DO AMAZONAS",
    "022106": "(DCAM) - DEFESA CIVIL DO AMAZONAS",
    "022701": "(FRAI) - FUNDO DE RESERVA PARA AS AÇÕES DE INTELIGÊNCIA",
    "022702": "(FUNESBOM) - FUNDO ESPECIAL DO CORPO DE BOMBEIROS MILITAR DO ESTADO DO AMAZONAS",
    "022703": "(FESP) - FUNDO ESTADUAL DE SEGURANÇA PÚBLICA DO ESTADO DO AMAZONAS",
    "022704": "(FEPDEC) - FUNDO ESTADUAL DE PROTEÇÃO E DEFESA CIVIL",
    "022705": "(FUNEPCAM) - FUNDO ESTADUAL PARA APARELHAMENTO E OPERACIONALIZACAO DAS ATIVIDADES DA POLICIA CIVIL DO ESTADO DO AMAZONAS",
    "024701": "(FUNDPAM) - FUNDO ESPECIAL DA DEFENSORIA PÚBLICA DO ESTADO DO  AMAZONAS",
    "025101": "(SEINFRA) - SECRETARIA DE ESTADO DE INFRAESTRUTURA",
    "025203": "(SNPH) - SUPERINTENDÊNCIA ESTADUAL DE NAVEGAÇÃO, PORTOS E HIDROVIAS",
    "025704": "(FIDEAM) - FUNDO DE INFRAESTRUTURA E DESENVOLVIMENTO DO ESTADO DO AMAZONAS",
    "028101": "(SEDUC) - SECRETARIA DE ESTADO DE EDUCAÇÃO E DESPORTO",
    "028102": "(UGPADEAM) - UNIDADE DE GERENCIAMENTO DO PROGRAMA DE ACERELACAO DO DESENVOLVIMENTO DA EDUCACAO DO ESTADO DO AMAZONAS",
    "028201": "(CETAM) - CENTRO DE EDUCAÇÃO TECNOLÓGICA DO AMAZONAS",
    "028301": "(FUNTEC) - FUNDAÇÃO TELEVISÃO E RÁDIO CULTURA DO AMAZONAS",
    "028302": "(FAAR) - FUNDAÇÃO AMAZONAS DE ALTO RENDIMENTO",
    "030101": "(SEMA) - SECRETARIA DE ESTADO DO MEIO AMBIENTE",
    "030201": "(IPAAM) - INSTITUTO DE PROTEÇÃO AMBIENTAL DO AMAZONAS",
    "030701": "(FEMA) - FUNDO ESTADUAL DO MEIO AMBIENTE",
    "030702": "(FERH/AM) - FUNDO ESTADUAL DE RECURSOS HÍDRICOS",
    "030703": "(FEMUCS) - FUNDO ESTADUAL DE MUDANÇAS CLIMÁTICAS, CONSERVAÇÃO AMBIENTAL E SERVIÇOS AMBIENTAIS",
    "031101": "(SEAS) - SECRETARIA DE ESTADO DA ASSISTÊNCIA SOCIAL E COMBATE A FOME",
    "031701": "(FEAS) - FUNDO ESTADUAL DE ASSISTÊNCIA SOCIAL",
    "037101": "(SECOM) - SECRETARIA DE ESTADO DE COMUNICAÇÃO SOCIAL",
    "040101": "(SERFI) - SECRETARIA DE ESTADO DE RELAÇÕES FEDERATIVAS E INTERNACIONAIS",
    "040102": "(ERGSP) - ESCRITÓRIO DE REPRESENTAÇÃO DO ESTADO EM SÃO PAULO",
    "041101": "(SEAP) - SECRETARIA DE ESTADO DE ADMINISTRAÇÃO PENITENCIÁRIA",
    "041701": "(FUPEAM) - FUNDO PENITENCIÁRIO DO ESTADO DO AMAZONAS",
    "042101": "(SEDEL) - SECRETARIA DE ESTADO DO DESPORTO E LAZER",
    "042701": "(FEEL) - FUNDO ESTADUAL DE ESPORTE E LAZER",
    "043101": "(SEDURB) - SECRETARIA DE ESTADO DE DESENVOLVIMENTO URBANO E METROPOLITANO",
    "043102": "(UGPE) - UNIDADE GESTORA DE PROJETOS ESPECIAIS",
    "043201": "(SUHAB) - SUPERINTENDÊNCIA ESTADUAL DE HABITAÇÃO",
    "043501": "(COSAMA) - COMPANHIA DE SANEAMENTO DO AMAZONAS S/A",
    "043701": "(FEH) - FUNDO ESTADUAL DE HABITAÇÃO",
    "043702": "(FERMM) - FUNDO ESPECIAL DA REGIÃO METROPOLITANA DE MANAUS",
    "044101": "(SEMIG) - SECRETARIA DE ESTADO DE ENERGIA, MINERAÇÃO E GÁS",
    "044501": "(CIGAS) - COMPANHIA DE GÁS DO ESTADO DO AMAZONAS",
    "045101": "(SEPET) - SECRETARIA DE ESTADO DE PROTECAO ANIMAL",
    "046101": "(SEPCD) - SECRETARIA DE ESTADO DOS DIREITOS DA PESSOA COM DEFICIENCIA",
    "046701": "(FEAPD) - FUNDO ESTADUAL DE APOIO A PESSOA COM DEFICIÊNCIA"
}

def raspar_contratos():
    # Cria e abre o arquivo CSV para escrita
    with open("contratos_amazonas.csv", mode="w", newline="", encoding="utf-8") as arquivo_csv:
        escritor = csv.writer(arquivo_csv, delimiter=";")
        
        # Escreve o cabeçalho
        escritor.writerow(["Orgao_Publico", "CNPJ_Fornecedor", "Data_Assinatura", "Descricao_Contrato", "Valor_Unitario", "Valor_Final"])

        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Content-Type': 'application/x-www-form-urlencoded'
        }

        # Loop passando por cada órgão público
        for ug_codigo, ug_nome in UNIDADES_GESTORAS.items():
            print(f"Coletando dados de: {ug_nome} ({ug_codigo})...")
            
            # Este payload simula o clique no botão "Consultar"
            payload = {
                'method': 'Consultar',
                'counidadegestora': ug_codigo,
                'inSituacao': '', # Vazio traz Vigentes e Não Vigentes. Se quiser só vigentes, mude para 'V'
            }

            try:
                # Faz a requisição POST
                resposta = requests.post(URL_BUSCA, data=payload, headers=headers)
                resposta.raise_for_status()

                # Faz o parse do HTML retornado
                soup = BeautifulSoup(resposta.text, 'html.parser')
                tabela = soup.find('table', id='tabela')

                if not tabela:
                    print(f"Nenhuma tabela encontrada para {ug_nome}.")
                    continue

                linhas = tabela.find('tbody').find_all('tr')
                
                for linha in linhas:
                    colunas = linha.find_all('td')
                    
                    if len(colunas) >= 14:
                        # O split() quebra nos espaços/enters e o join() junta com um espaço simples
                        orgao = " ".join(colunas[1].text.split())
                        cnpj = " ".join(colunas[4].text.split())
                        data_assinatura = " ".join(colunas[8].text.split())
                        descricao = " ".join(colunas[9].text.split())
                        valorUnitário = " ".join(colunas[10].text.split())
                        valorFinal = " ".join(colunas[11].text.split())
                        # print(colunas)

                        escritor.writerow([orgao, cnpj, data_assinatura, descricao, valorUnitário, valorFinal])

                print(f"-> {len(linhas)} contratos salvos.\n")
                
                # Pausa de 2 segundos para não sobrecarregar/derrubar o servidor deles
                time.sleep(2)

            except Exception as e:
                print(f"Erro ao processar {ug_nome}: {e}")

    print("Processo concluído! Verifique o arquivo 'contratos_amazonas.csv'.")

# Executa o scraper
if __name__ == "__main__":
    raspar_contratos()